# Generated by Django 2.2.4 on 2019-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('to_due_date', models.DateTimeField()),
                ('priority', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('TODO', 'todo'), ('DONE', 'done'), ('REMOVE', 'remove')], default='TODO', max_length=6)),
            ],
        ),
    ]
