# Generated by Django 2.2.4 on 2019-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
